name: vae
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9.*
  - pytorch=1.13.0=*cuda*
  - cudatoolkit=11.7
  - torchvision=0.14.0
  - pip:
    - tensorboard==2.11.*
    - torch-tb-profiler==0.4.1
    - pytorch-lightning==1.5.6
    - PyYAML==6.0
    - torchsummary==1.5.1
